### ISSUE TITLE
Add `conda-forge/cuda` team as maintainers?

### ISSUE THREAD

**Issue by leofang** [conda-forge/nvmath-feedstock#9]
@bdice brought up about this offline. We should discuss in the next sync-up.

**Comment by leofang** [comment]
@bdice (or @jakirkham), could you remind me if this was already discussed in recent sync-ups?

**Comment by bdice** [comment]
I do not know if this has been discussed, I have missed the last couple meetings. I would favor adding @conda-forge/cuda as a maintainer.
